const DESIGNATIONS = {
  DEPARTMENT_CHAIRMAN: "Department Chairman",
  COLLEGE_DEAN: "College Dean",
  DIRECTOR_STUDENT_AFFAIRS: "Director of Student Affairs",
  NSTP_DIRECTOR: "NSTP Director",
  EXECUTIVE_OFFICER: "Executive Officer",
  DEAN_GRADUATE_SCHOOL: "Dean of Graduate School",
};

const UNDERGRAD_DESIGNATIONS = [
  DESIGNATIONS.DEPARTMENT_CHAIRMAN,
  DESIGNATIONS.COLLEGE_DEAN,
  DESIGNATIONS.DIRECTOR_STUDENT_AFFAIRS,
  DESIGNATIONS.NSTP_DIRECTOR,
  DESIGNATIONS.EXECUTIVE_OFFICER,
];

const UNDERGRAD_PREREQS = {
  [DESIGNATIONS.DEPARTMENT_CHAIRMAN]: [],
  [DESIGNATIONS.COLLEGE_DEAN]: [DESIGNATIONS.DEPARTMENT_CHAIRMAN],
  [DESIGNATIONS.DIRECTOR_STUDENT_AFFAIRS]: [DESIGNATIONS.COLLEGE_DEAN],
  [DESIGNATIONS.NSTP_DIRECTOR]: [DESIGNATIONS.DIRECTOR_STUDENT_AFFAIRS],
  [DESIGNATIONS.EXECUTIVE_OFFICER]: [DESIGNATIONS.NSTP_DIRECTOR],
};

const isUndergradDesignation = (designation) =>
  UNDERGRAD_DESIGNATIONS.includes(designation);

module.exports = {
  DESIGNATIONS,
  UNDERGRAD_DESIGNATIONS,
  UNDERGRAD_PREREQS,
  isUndergradDesignation,
};
